# Generated by Django 4.2.2 on 2023-06-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("albunes", "0002_alter_album_song"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="song",
            new_name="song_id",
        ),
    ]
