# Generated by Django 4.2.2 on 2023-06-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(),
        ),
    ]
