# Generated by Django 4.2.2 on 2023-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_cliente_puntos_alter_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='MontoTotal',
            field=models.FloatField(null=True),
        ),
    ]
