CREATE TABLE "alumnos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "edad" int NOT NULL
);

CREATE TABLE "salon" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ano_escolar" int NOT NULL,
  "seccion" varchar(1) NOT NULL,
  "id_alumno" int NOT NULL,
  "id_profesor" int NOT NULL
);

CREATE TABLE "cursos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "id_alumno" int NOT NULL,
  "id_profesor" int NOT NULL,
  "nota_bimestre_1" varchar DEFAULT '--',
  "nota_bimestre_2" varchar DEFAULT '--',
  "nota_bimestre_3" varchar DEFAULT '--',
  "nota_bimestre_4" varchar DEFAULT '--'
);

CREATE TABLE "salon_cursos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_salon" int NOT NULL,
  "id_curso" int NOT NULL
);

CREATE TABLE "profesores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL
);

ALTER TABLE "salon" ADD FOREIGN KEY ("id_alumno") REFERENCES "alumnos" ("id");

ALTER TABLE "salon" ADD FOREIGN KEY ("id_profesor") REFERENCES "profesores" ("id");

ALTER TABLE "cursos" ADD FOREIGN KEY ("id_alumno") REFERENCES "alumnos" ("id");

ALTER TABLE "cursos" ADD FOREIGN KEY ("id_profesor") REFERENCES "profesores" ("id");

ALTER TABLE "salon_cursos" ADD FOREIGN KEY ("id_salon") REFERENCES "salon" ("id");

ALTER TABLE "salon_cursos" ADD FOREIGN KEY ("id_curso") REFERENCES "cursos" ("id");