# Generated by Django 4.2.2 on 2023-06-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0002_alter_artist_album"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="album",
            new_name="album_id",
        ),
    ]
