# Generated by Django 4.2.2 on 2023-06-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artistas', '0001_initial'),
        ('Playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('artist_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Artistas.artist')),
                ('playlist_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Playlists.playlist')),
            ],
        ),
    ]
