# Generated by Django 4.2.1 on 2023-06-04 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_curso_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.alumno')),
            ],
        ),
    ]
