# Generated by Django 4.2.1 on 2023-06-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='documentoIdentidad',
            new_name='tipoDocumento',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='documentoIdentidad',
            new_name='tipoDocumento',
        ),
        migrations.AddField(
            model_name='autor',
            name='numeroDocumento',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userapp',
            name='numeroDocumento',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
