# Generated by Django 4.2.1 on 2023-06-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_alter_autor_books_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolibro',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libro.book'),
            preserve_default=False,
        ),
    ]
