# Generated by Django 4.2.1 on 2023-05-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Algebra', 'Algebra'), ('Algoritmos y Estructura de Datos', 'Algoritmos y Estructura de Datos'), ('Algoritmos y Estructura de Datos II', 'Algoritmos y Estructura de Datos II'), ('Probabilidad y Estadistica', 'Probabilidad y Estadistica'), ('Administracion', 'Administracion'), ('Sistemas y Organizaciones', 'Sistemas y Organizaciones'), ('Logica y Matematica Computacional', 'Logica y Matematica Computacional'), ('Base de Datos', 'Base de Datos')], max_length=50, verbose_name='Nombre Curso')),
                ('salon', models.CharField(choices=[('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('107', '107'), ('108', '108'), ('109', '109'), ('110', '110'), ('111', '111'), ('112', '112')], max_length=5, verbose_name='Nombre Salon')),
            ],
        ),
    ]
