# Generated by Django 4.2.1 on 2023-05-27 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdminColegio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('identifAlumno', models.CharField(max_length=12, verbose_name='Identificador')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdminColegio.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('identifProfesor', models.CharField(max_length=12, verbose_name='Identificador')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('experiencia', models.IntegerField(verbose_name='Años Experiencia')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdminColegio.curso')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroMatricula', models.IntegerField(verbose_name='Numero Matricula')),
                ('periodoLectivo', models.CharField(max_length=20, verbose_name='Periodo Lectivo')),
                ('identifAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdminColegio.alumno')),
            ],
        ),
    ]
