# Generated by Django 4.2.2 on 2023-06-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
        ('tipo', '0001_initial'),
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='user',
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='marca.marca'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='tipo.tipo'),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
