# Generated by Django 4.2.1 on 2023-06-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numeroDocumento', models.CharField(max_length=13)),
                ('estado', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('Anio', models.IntegerField()),
                ('Mes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numeroDocumento', models.CharField(max_length=13)),
                ('estado', models.CharField(max_length=3)),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.nacionalidad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.sexo')),
                ('tipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.documentoidentidad')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota1', models.FloatField(blank=True, max_length=4, null=True)),
                ('nota2', models.FloatField(blank=True, max_length=4, null=True)),
                ('nota3', models.FloatField(blank=True, max_length=4, null=True)),
                ('nota4', models.FloatField(blank=True, max_length=4, null=True)),
                ('promedio', models.FloatField(blank=True, max_length=4, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.alumno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.curso')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.periodo')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a1', models.CharField(blank=True, max_length=2, null=True)),
                ('a2', models.CharField(blank=True, max_length=2, null=True)),
                ('a3', models.CharField(blank=True, max_length=2, null=True)),
                ('a4', models.CharField(blank=True, max_length=2, null=True)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.alumno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.curso')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.periodo')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.nacionalidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.sexo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipoDocumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.documentoidentidad'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numeroDocumento', models.CharField(max_length=13)),
                ('estado', models.CharField(max_length=3)),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.nacionalidad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.sexo')),
                ('tipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.documentoidentidad')),
            ],
        ),
    ]
