# Generated by Django 4.2.2 on 2023-06-10 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cashier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(default="", max_length=200)),
                ("id_card_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(default="", max_length=200)),
                ("id_card_number", models.CharField(max_length=20)),
                ("points", models.IntegerField(default=0)),
                ("creation_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="IdCardType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_card_type", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("igv", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.cashier"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.CharField(max_length=200)),
                ("stock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.invoice"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sale.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="id_card_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sale.idcardtype",
            ),
        ),
        migrations.AddField(
            model_name="cashier",
            name="id_card_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sale.idcardtype",
            ),
        ),
    ]
