# Generated by Django 4.2.2 on 2023-06-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0002_alter_invoice_cashier"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
