# Generated by Django 4.2.2 on 2023-06-11 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0003_invoice_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="igv",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="subtotal",
        ),
    ]
