# Generated by Django 4.2.2 on 2023-06-27 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("singers", "0002_rename_album_id_singer_album"),
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=250)),
                ("date", models.DateField(auto_now=True)),
                ("description", models.CharField(max_length=300, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="singers.singer",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="playlists.playlist",
                    ),
                ),
            ],
        ),
    ]
