# Generated by Django 4.2.1 on 2023-05-24 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Biography",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(blank=True, max_length=200, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("religion", models.CharField(max_length=200)),
                ("study_center", models.TextField()),
                ("career", models.TextField()),
                ("website", models.CharField(max_length=200)),
                ("employer", models.CharField(max_length=200)),
                ("created_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "birth_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nationality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biography.nationality",
                    ),
                ),
            ],
        ),
    ]
