# Generated by Django 4.2.1 on 2023-05-30 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('religiion', models.CharField(max_length=200)),
                ('educacion', models.TextField()),
                ('ocupacion', models.TextField(max_length=200)),
                ('empleador', models.TextField(max_length=200)),
                ('sitio_web', models.CharField(max_length=200)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.nationality')),
                ('nombre_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
