# Generated by Django 4.2.1 on 2023-06-01 22:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subBiblioteca', '0003_autor_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documentoIdentidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.documentoidentidad')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.nacionalidad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.sexo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='documentoIdentidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.documentoidentidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.sexo'),
        ),
    ]
