# Generated by Django 4.2.1 on 2023-06-01 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subBiblioteca', '0004_documentoidentidad_sexo_userapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLibro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('diasPrestamo', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.userapp')),
            ],
        ),
    ]
