# Generated by Django 4.2.1 on 2023-06-04 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('dni', models.CharField(default='72455505', max_length=10)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('img_path', models.CharField(max_length=500, null=True)),
                ('availability', models.PositiveIntegerField(default=5)),
                ('password', models.CharField(default='1111111', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('max_students', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('dni', models.CharField(default='72455505', max_length=10)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('img_path', models.CharField(max_length=500, null=True)),
                ('availability', models.PositiveIntegerField(default=5)),
                ('password', models.CharField(default='1111111', max_length=10)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.alumnos')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.aula')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.ciclo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.userschool')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(max_length=500, null=True)),
                ('availability', models.PositiveIntegerField(default=25)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.ciclo')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.ciclo'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('attendance', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.alumnos')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.userschool')),
            ],
        ),
    ]
