# Generated by Django 4.2.1 on 2023-06-05 03:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('dni', models.CharField(default='72443245', max_length=10)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('img_path', models.CharField(max_length=500, null=True)),
                ('availability', models.PositiveSmallIntegerField(default=5)),
                ('password', models.CharField(default='1111111', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('max_student', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(max_length=200, null=True)),
                ('availability', models.PositiveSmallIntegerField(default=5)),
                ('img_path', models.CharField(max_length=500, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioColegio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('dni', models.CharField(default='72443245', max_length=10)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('img_path', models.CharField(max_length=500, null=True)),
                ('availability', models.PositiveSmallIntegerField(default=5)),
                ('password', models.CharField(default='1111111', max_length=10)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.curso')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.curso')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.ciclo')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.aula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.alumno')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.usuariocolegio')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.ciclo'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateField(default=datetime.date.today)),
                ('attendance', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.alumno')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.usuariocolegio')),
            ],
        ),
    ]
