# Generated by Django 4.2.1 on 2023-06-04 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colegio.curso'),
        ),
    ]
