# Generated by Django 4.2.2 on 2023-06-27 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_rename_song_album_song_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="album",
            old_name="song_id",
            new_name="song",
        ),
    ]
