# Generated by Django 4.2.2 on 2023-06-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artistas", "0002_alter_artist_album"),
        ("playlist", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="artist",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="artistas.artist",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="playlist",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="playlist.playlist",
            ),
        ),
    ]
