# Generated by Django 4.2.1 on 2023-06-01 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='books',
            field=models.ManyToManyField(to='subBiblioteca.book'),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subBiblioteca.nacionalidad'),
        ),
    ]
