# Generated by Django 4.2.1 on 2023-06-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subBiblioteca', '0002_nacionalidad_autor_books_autor_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'IDK')], max_length=1, null=True),
        ),
    ]
