# Generated by Django 4.2.1 on 2023-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colegio', '0002_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matriculado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='edad',
            field=models.IntegerField(blank=True),
        ),
    ]
