# Generated by Django 4.2.1 on 2023-06-02 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0003_alter_enrollment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="enrollment",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="cicle",
        ),
        migrations.RemoveField(
            model_name="graderecord",
            name="enrollment",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="students",
                to="control.enrollment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graderecord",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="control.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="graderecord",
            name="grade",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="fullname",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="fullname",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.DeleteModel(
            name="Cicle",
        ),
    ]
