# Generated by Django 4.2.1 on 2023-06-02 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0004_remove_attendancerecord_enrollment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.CharField(max_length=100)),
                ("creation_date", models.DateField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="day",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="control.day"
            ),
        ),
        migrations.AddField(
            model_name="graderecord",
            name="day",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="control.day"
            ),
        ),
    ]
