# Generated by Django 4.2.1 on 2023-06-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0005_day_attendancerecord_day_graderecord_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="classroom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="control.classroom",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graderecord",
            name="classroom",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="control.classroom",
            ),
            preserve_default=False,
        ),
    ]
