# Generated by Django 4.2.1 on 2023-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control", "0006_attendancerecord_classroom_graderecord_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graderecord",
            name="grade",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
