"""database minimarket

Revision ID: 156cacc8e688
Revises: 
Create Date: 2023-05-23 21:33:09.239248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156cacc8e688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('dni', sa.String(length=12), nullable=False),
    sa.Column('celular', sa.String(length=9), nullable=True),
    sa.Column('direccion', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['model_categoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['model_rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('model_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cliente', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('Cantidad', sa.Integer(), nullable=False),
    sa.Column('MontoTotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['model_producto.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['model_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_factura')
    op.drop_table('model_user')
    op.drop_table('model_producto')
    op.drop_table('model_rol')
    op.drop_table('model_cliente')
    op.drop_table('model_categoria')
    # ### end Alembic commands ###
