"""modificando database factura

Revision ID: e14ad646334f
Revises: 156cacc8e688
Create Date: 2023-05-23 23:28:27.066540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14ad646334f'
down_revision = '156cacc8e688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'model_cliente', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
