# Generated by Django 4.2.1 on 2023-06-02 01:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documentoIdentidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.documentoidentidad')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.nacionalidad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.sexo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLibro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('diasPrestamo', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.ManyToManyField(to='libro.autor')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='books',
            field=models.ManyToManyField(to='libro.book'),
        ),
        migrations.AddField(
            model_name='autor',
            name='documentoIdentidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.documentoidentidad'),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.nacionalidad'),
        ),
        migrations.AddField(
            model_name='autor',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.sexo'),
        ),
    ]
