# Generated by Django 4.2.1 on 2023-06-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_rename_documentoidentidad_autor_tipodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='books',
            field=models.ManyToManyField(null=True, to='libro.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, to='libro.autor'),
        ),
    ]
