# Generated by Django 4.2.2 on 2023-06-27 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Singer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("musical_genre", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("img_url", models.CharField(max_length=500)),
                (
                    "album_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="albums.album"
                    ),
                ),
            ],
        ),
    ]
