# Generated by Django 4.2.2 on 2023-06-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='matricula',
            field=models.CharField(default='02', max_length=50),
            preserve_default=False,
        ),
    ]
