# Generated by Django 4.2.2 on 2023-06-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0002_avion_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='fechaTakeOff',
            field=models.DateTimeField(),
        ),
    ]
